[package]
name = "word_count_rust"
version = "0.1.0"
authors = ["Alexander Niederbühl <a.niederbuehl@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1"

[dependencies.pyo3]
version = "0.8.3"
features = ["extension-module"]

[lib]
crate-type = ["cdylib"]
